AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  The Hello World ECR Repo
Parameters:
  OU:
    Type: String
    Default: demo
  PlatForm:
    Type: String
    Default: dev
  Project:
    Type: String
    Default: hworld

Resources:
  HWorldEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${OU}-ecr-${PlatForm}-${Project}-repo

Outputs:
  HWorldEcrRepoArn:
    Value: !GetAtt HWorldEcrRepo.Arn
    Export:
      Name: HWorldEcrRepoArn
